### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'useMemo')

### ISSUE THREAD

**Issue by craftByElla** [Bitnoise/react-scheduler#115]
Hello,

I'm currently facing an issue with the @bitnoi.se/react-scheduler component in my Next.js project. After integrating the scheduler into my application, I consistently receive the following runtime error:

TypeError: Cannot read properties of null (reading 'useMemo')

Here is a brief overview of my setup:

Next.js version: 12.1.6
React version: 18.1.0
@bitnoi.se/react-scheduler version: 0.2.0

by the way I'm a beginner dev so sorry if i missed something.
[Gantt-React.txt](https://github.com/Bitnoise/react-scheduler/files/15111772/Gantt-React.txt)
[Home.txt](https://github.com/Bitnoise/react-scheduler/files/15111773/Home.txt)

**Comment by craftByElla** [comment]
I Even tried #69 but same error still

**Comment by kernex** [comment]
Same error here.

**Comment by ZiangTian** [comment]
same

**Comment by amjadmak** [comment]
Same Here. using react 18

**Comment by WenhaoYou1** [comment]
> @craftByElla @ZiangTian @kernex
> 
> I solved it by changing the version of react and react-dom in package.json as below First: Delete `node_modules ` and `package-lock.json ` Second: Go to `package.json` and change the version of react and react-dom as below
> 
> ```
>     "react": "18.2.0",
>     "react-dom": "18.2.0",
> ```
> 
> run `npm i`

It works. Thx.

**Comment by inno-zunaid** [comment]
Hi my 
 "react": "^18.3.1",
 "react-dom": "^18.3.1",

i don't want to degrade the react version is there any solution for this..

**Comment by domme1908** [comment]
Hi - Same here, even with react 18.2.0 and react-dom 18.2.0

**Comment by nikolaspoczekaj** [comment]
Hello, same here.

**Comment by mGasiorek998** [comment]
Hi, with the upcoming version we'll update react version to the newest one, so this issue should be fixed. Stay tuned!

**Comment by whittssg** [comment]
@mGasiorek998 I saw a few new versions since this but I still get the useMemo error on the new ones? Was it fixed or do we still need to downgrade ? Thanks
